"""
Kuratierte Liste der zu scannenden VCs.

Jeder Eintrag:
    name    -> Anzeigename
    website -> Karriere-/Website-Link (für die UI)
    ats     -> eines von: personio | greenhouse | lever | ashby | recruitee | workable
                          | join | getro | smartrecruiters | trakstar | breezy
    slug    -> die firmenspezifische Kennung im jeweiligen ATS

Eintraege mit ats = None sind VCs OHNE auslesbaren Karrierefeed. Sie stehen im Dropdown der
Webseite, werden aber nicht gescannt (die Seite zeigt dort einen Hinweis auf die Karriereseite).
Ein VC kann mehrere Eintraege haben (mehrere Feeds), der Name muss dann identisch sein.

So findest du den slug:
    - Personio:   URL der Karriereseite ist meist {slug}.jobs.personio.de
    - Greenhouse: boards.greenhouse.io/{slug}  oder im Bewerbungslink
    - Lever:      jobs.lever.co/{slug}
    - Ashby:      jobs.ashbyhq.com/{slug}
    - Recruitee:  {slug}.recruitee.com
    - Workable:   apply.workable.com/{slug}
    - JOIN:       join.com/companies/{slug}
    - Getro:      "<board-host>/<company-slug>", z.B. "jobs.earlybird.com/earlybird-venture-capital".
                  Das Board listet auch Portfolio-Stellen; der Adapter filtert auf die
                  Stellen des VCs selbst. Den company-slug findest du in der URL
                  <board-host>/companies/<company-slug>.

    - SmartRecruiters: "<company>" oder "<company>|<Stichwort>". Mit Stichwort werden nur Stellen
                  behalten, deren Titel es enthaelt (GFC: "RocketInternet|Global Founders Capital").
    - Trakstar:   {slug}.hire.trakstar.com
    - Breezy HR:  {slug}.breezy.hr

Bevorzugt den direkten ATS des VCs (Personio, Ashby ...) gegenüber Getro, wenn bekannt.

Neue VCs einfach unten anhängen. Falsche/leere Feeds liefern einfach 0 Stellen
und stören den Rest nicht. Steht im Actions-Log ("X Stellen vom Feed") dauerhaft 0,
stimmt entweder ats/slug nicht oder der VC hat gerade nichts offen.

Stand (18.09.2026): 200 VCs, davon 45 mit Feed. Feeds wurden ueber den echten Kontonamen
verifiziert (Verwechslungen mit gleichnamigen Firmen ausgeschlossen). Der JOIN-Adapter ist an
einer echten Stelle bestaetigt (Alstin Capital). Bei VCs mit 0 Stellen ist der Feed erreichbar,
aber aktuell leer.
"""

VCS: list[dict] = [
    {
        "name": "2150",
        "website": "https://www.2150.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "468 Capital",
        "website": "https://468cap.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Accel",
        "website": "https://www.accel.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Acton Capital",
        "website": "https://www.actoncapital.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Ada Ventures",
        "website": "https://www.adaventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Addition",
        "website": "https://addition.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Allianz X",
        "website": "https://allianzx.com/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Alstin Capital",
        "website": "https://alstin.capital/careers",
        "ats": "join",
        "slug": "alstin",
    },
    {
        "name": "Alven",
        "website": "https://alven.co/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Ananda Impact Ventures",
        "website": "https://ananda.vc",
        "ats": "recruitee",
        "slug": "anandaventuresgmbh",
    },
    {
        "name": "Andreessen Horowitz",
        "website": "https://a16z.com/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Anthemis Group",
        "website": "https://www.anthemis.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Antler",
        "website": "https://www.antler.co/careers",
        "ats": "join",
        "slug": "antler",
    },
    {
        "name": "APX",
        "website": "https://apx.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Atlantic Food Labs",
        "website": "https://www.foodlabs.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Atlantic Labs",
        "website": "https://atlanticlabs.com/careers",
        "ats": "join",
        "slug": "atlanticlabs",
    },
    {
        "name": "Atomico",
        "website": "https://atomico.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Auxxo",
        "website": "https://auxxo.de",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Backed VC",
        "website": "https://www.backed.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Bain Capital Ventures",
        "website": "https://baincapitalventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Balderton Capital",
        "website": "https://www.balderton.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "BASF Venture Capital",
        "website": "https://www.basf.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Battery Ventures",
        "website": "https://battery.com",
        "ats": "join",
        "slug": "battery",
    },
    {
        "name": "BayBG",
        "website": "https://baybg.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Bayern Kapital",
        "website": "https://bayernkapital.de",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Benchmark",
        "website": "https://benchmark.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Bertelsmann Investments",
        "website": "https://www.bertelsmann-investments.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Bessemer Venture Partners",
        "website": "https://www.bvp.com/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "BITKRAFT Ventures",
        "website": "https://bitkraft.vc/careers",
        "ats": "greenhouse",
        "slug": "bitkraft",
    },
    {
        "name": "Blossom Capital",
        "website": "https://www.blossomcap.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "BMW i Ventures",
        "website": "https://www.bmwiventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Bond",
        "website": "https://www.bondcap.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Bpifrance",
        "website": "https://www.bpifrance.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Brandenburg Kapital",
        "website": "https://www.brandenburg-kapital.de",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Breakthrough Energy Ventures",
        "website": "https://www.breakthroughenergy.org/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Breega",
        "website": "https://www.breega.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "btov / b2venture",
        "website": "https://www.b2venture.vc",
        "ats": "join",
        "slug": "b2venture",
    },
    {
        "name": "byFounders",
        "website": "https://byfounders.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Calm/Storm Ventures",
        "website": "https://www.calmstorm.vc/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Capital300",
        "website": "https://capital300.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "capnamic Ventures",
        "website": "https://capnamic.com/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Cathay Innovation",
        "website": "https://cathayinnovation.com",
        "ats": "join",
        "slug": "cathayinnovation",
    },
    {
        "name": "Cavalry Ventures",
        "website": "https://cavalry.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Cherry Ventures",
        "website": "https://cherry.vc",
        "ats": "getro",
        "slug": "talent.cherry.vc/cherry-ventures",
    },
    {
        "name": "Cherry Ventures",
        "website": "https://cherry.vc",
        "ats": "workable",
        "slug": "cherry-ventures",
    },
    {
        "name": "Cisco Investments",
        "website": "https://www.ciscoinvestments.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Coatue",
        "website": "https://www.coatue.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "coparion",
        "website": "https://join.com/companies/coparion",
        "ats": "join",
        "slug": "coparion",
    },
    {
        "name": "Creandum",
        "website": "https://creandum.com",
        "ats": "workable",
        "slug": "creandum",
    },
    {
        "name": "Creathor Ventures",
        "website": "https://www.creathor.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Cusp Capital",
        "website": "https://cuspcapital.com",
        "ats": "join",
        "slug": "cuspcapital",
    },
    {
        "name": "Daphni",
        "website": "https://www.daphni.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Dawn Capital",
        "website": "https://www.dawncapital.com/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Deutsche Telekom Capital Partners",
        "website": "https://www.dtcp.capital/careers",
        "ats": "breezy",
        "slug": "dtcp",
    },
    {
        "name": "DN Capital",
        "website": "https://dncapital.com",
        "ats": "trakstar",
        "slug": "dncapital",
    },
    {
        "name": "Dragoneer",
        "website": "https://www.dragoneer.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "DST Global",
        "website": "https://dst.global/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Earlybird",
        "website": "https://earlybird.com",
        "ats": "personio",
        "slug": "earlybirdvc-gmbh",
    },
    {
        "name": "eCAPITAL",
        "website": "https://ecapital.vc/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Eight Roads",
        "website": "https://eightroads.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Elaia",
        "website": "https://elaia.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Energy Impact Partners",
        "website": "https://www.energyimpactpartners.com/careers",
        "ats": "join",
        "slug": "energyimpactpartners",
    },
    {
        "name": "Entrepreneur First",
        "website": "https://www.joinef.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "EQT Ventures",
        "website": "https://eqtgroup.com",
        "ats": "join",
        "slug": "eqtventures",
    },
    {
        "name": "ETF Partners",
        "website": "https://etfpartners.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Eurazeo",
        "website": "https://www.eurazeo.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "European Investment Fund (EIF)",
        "website": "https://eif.org",
        "ats": None,
        "slug": None,
    },
    {
        "name": "EWOR",
        "website": "https://www.ewor.com",
        "ats": "join",
        "slug": "ewor",
    },
    {
        "name": "Extantia Capital",
        "website": "https://join.com/companies/extantia",
        "ats": "join",
        "slug": "extantia",
    },
    {
        "name": "Fabric Ventures",
        "website": "https://www.fabric.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "FinTech Collective",
        "website": "https://fintechcollective.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "FirstMark",
        "website": "https://firstmark.com/join",
        "ats": None,
        "slug": None,
    },
    {
        "name": "firstminute capital",
        "website": "https://www.firstminute.capital",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Fly Ventures",
        "website": "https://fly.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Forbion",
        "website": "https://forbion.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Foundamental",
        "website": "https://www.foundamental.com",
        "ats": "join",
        "slug": "foundamental",
    },
    {
        "name": "Founderful",
        "website": "https://www.founderful.com/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Founders Fund",
        "website": "https://foundersfund.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Freigeist Capital",
        "website": "https://freigeist.com/career",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Fund F",
        "website": "https://www.fund-f.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "General Atlantic",
        "website": "https://www.generalatlantic.com/careers",
        "ats": "greenhouse",
        "slug": "generalatlantic",
    },
    {
        "name": "General Catalyst",
        "website": "https://www.generalcatalyst.com",
        "ats": "greenhouse",
        "slug": "generalcatalyst",
    },
    {
        "name": "Global Founders Capital",
        "website": "https://www.globalfounders.vc",
        "ats": "smartrecruiters",
        "slug": "RocketInternet|Global Founders Capital",
    },
    {
        "name": "Greycroft",
        "website": "https://greycroft.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Greylock",
        "website": "https://greylock.com/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "GV",
        "website": "https://www.gv.com/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Headline",
        "website": "https://headline.com",
        "ats": "join",
        "slug": "headline",
    },
    {
        "name": "Heartcore Capital",
        "website": "https://www.heartcore.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Hedosophia",
        "website": "https://hedosophia.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "High-Tech Gründerfonds (HTGF)",
        "website": "https://www.htgf.de/careers",
        "ats": "personio",
        "slug": "htgf",
    },
    {
        "name": "Highland Europe",
        "website": "https://highlandeurope.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Hoxton Ventures",
        "website": "https://hoxtonventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Hummingbird Ventures",
        "website": "https://www.hummingbird.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "HV Capital",
        "website": "https://hvcapital.com/careers",
        "ats": "ashby",
        "slug": "hv",
    },
    {
        "name": "IBB Ventures",
        "website": "https://www.ibbventures.de/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "ICONIQ Capital",
        "website": "https://iconiqcapital.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "IFB Innovationsstarter Hamburg",
        "website": "https://www.ifbhh.de/karriere",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Index Ventures",
        "website": "https://www.indexventures.com:443",
        "ats": "lever",
        "slug": "indexventures",
    },
    {
        "name": "Innovationsfonds Schleswig-Holstein",
        "website": "https://wtsh.de/karriere",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Inovia Capital",
        "website": "https://inovia.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Insight Partners",
        "website": "https://www.insightpartners.com/jobs",
        "ats": "smartrecruiters",
        "slug": "InsightPartners",
    },
    {
        "name": "Intel Capital",
        "website": "https://www.intelcapital.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Inventure",
        "website": "https://www.inventure.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "IVP",
        "website": "https://www.ivp.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "JOIN Capital",
        "website": "https://join-capital.com/",
        "ats": "personio",
        "slug": "join-capital",
    },
    {
        "name": "KfW Capital",
        "website": "https://www.kfw-capital.de/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Kibo Ventures",
        "website": "https://www.kiboventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Kima Ventures",
        "website": "https://www.kimaventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Kindred Capital",
        "website": "https://kindredcapital.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Kinnevik",
        "website": "https://www.kinnevik.com/career",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Kizoo Technology Capital",
        "website": "https://kizoo.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Kleiner Perkins",
        "website": "https://www.kleinerperkins.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Kompas VC",
        "website": "https://www.kompas.vc/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Kurma Partners",
        "website": "https://www.kurmapartners.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "La Famiglia",
        "website": "https://www.lafamiglia.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Lakestar",
        "website": "https://www.lakestar.com",
        "ats": "personio",
        "slug": "lakestar",
    },
    {
        "name": "Latitude",
        "website": "https://www.phoenixcourt.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Lifeline Ventures",
        "website": "https://www.lifelineventures.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Lightrock",
        "website": "https://lightrock.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Lightspeed Venture Partners",
        "website": "https://lsvp.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "LocalGlobe",
        "website": "https://www.phoenixcourt.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "LSP",
        "website": "https://eqtgroup.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Lunar Ventures",
        "website": "https://www.lunar.vc/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "M12",
        "website": "https://m12.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Maki.vc",
        "website": "https://maki.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Mangrove Capital Partners",
        "website": "https://www.mangrove.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Medicxi",
        "website": "https://www.medicxi.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Merantix Capital",
        "website": "https://www.merantix-capital.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Merck Ventures",
        "website": "https://merckventures.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "MMC Ventures",
        "website": "https://mmc.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Molten Ventures",
        "website": "https://www.moltenventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Motive Partners",
        "website": "https://motivepartners.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Mountain Partners",
        "website": "https://mountain-partners.ch/careers",
        "ats": "join",
        "slug": "mountain",
    },
    {
        "name": "NEA",
        "website": "https://nea.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Next47",
        "website": "https://www.n47.com",
        "ats": "greenhouse",
        "slug": "next47",
    },
    {
        "name": "Northzone",
        "website": "https://northzone.com",
        "ats": "personio",
        "slug": "northzone",
    },
    {
        "name": "Norwest",
        "website": "https://nvp.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Notion Capital",
        "website": "https://www.notioncapital.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Novartis Venture Fund",
        "website": "https://www.nvfund.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Octopus Ventures",
        "website": "https://octopusventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Pale Blue Dot",
        "website": "https://paleblue.vc/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Partech",
        "website": "https://partechpartners.com",
        "ats": "join",
        "slug": "partechpartners",
    },
    {
        "name": "Passion Capital",
        "website": "https://passioncapital.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Peak",
        "website": "https://peak.capital/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Picus Capital",
        "website": "https://www.picuscap.com/career",
        "ats": "join",
        "slug": "picuscap",
    },
    {
        "name": "Pioneer Fund",
        "website": "https://www.pioneerfund.vc/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Planet A Ventures",
        "website": "https://planeta.vc/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Plural VC",
        "website": "https://www.plural.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Point Nine",
        "website": "https://www.pointnine.com",
        "ats": "recruitee",
        "slug": "pointnine",
    },
    {
        "name": "Porsche Ventures",
        "website": "https://porsche.ventures",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Project A Ventures",
        "website": "https://www.project-a.vc/careers",
        "ats": "join",
        "slug": "project-a",
    },
    {
        "name": "Project A Ventures",
        "website": "https://www.project-a.vc/careers",
        "ats": "workable",
        "slug": "project-a",
    },
    {
        "name": "Prosus Ventures",
        "website": "https://prosus.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Qualcomm Ventures",
        "website": "https://www.qualcommventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Rebel Fund",
        "website": "https://www.rebelfund.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Redalpine",
        "website": "https://www.redalpine.com/career",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Redpoint eventures",
        "website": "https://www.redpoint.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Redstone",
        "website": "https://redstone.vc/careers",
        "ats": "personio",
        "slug": "redstone-digital-gmbh",
    },
    {
        "name": "Ribbit Capital",
        "website": "https://www.ribbitcap.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Robert Bosch Venture Capital",
        "website": "https://bosch.ventures",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Rocket Internet",
        "website": "https://rocket-internet.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Seaya",
        "website": "https://seaya.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Senovo",
        "website": "https://join.com/companies/senovo",
        "ats": "join",
        "slug": "senovo",
    },
    {
        "name": "Sequoia Capital",
        "website": "https://sequoiacap.com/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "SevenVentures",
        "website": "https://www.commerceandventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Singular",
        "website": "https://www.singular.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Sofina",
        "website": "https://sofinagroup.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Sofinnova Partners",
        "website": "https://sofinnovapartners.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "SoftBank Vision Fund",
        "website": "https://visionfund.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Speedinvest",
        "website": "https://www.speedinvest.com",
        "ats": "getro",
        "slug": "careers.speedinvest.com/speedinvest",
    },
    {
        "name": "Statkraft Ventures",
        "website": "https://www.statkraftventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Stride.VC",
        "website": "https://stride.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Summit Partners",
        "website": "https://www.summitpartners.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Swisscom Ventures",
        "website": "https://www.swisscom.ch/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Target Global",
        "website": "https://targetglobal.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "TCV",
        "website": "https://www.tcv.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Technologiegründerfonds Sachsen",
        "website": "https://www.cfh.de",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Tengelmann Ventures",
        "website": "https://tengelmann-ventures.com/career",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Tiger Global",
        "website": "https://www.tigerglobal.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Trade Ventures",
        "website": "https://www.tradeventures.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Trind Ventures",
        "website": "https://trind.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "TVM Capital Life Science",
        "website": "https://tvm-capital.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Union Square Ventures",
        "website": "https://www.usv.com/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "UVC Partners",
        "website": "https://www.uvcpartners.com/jobs",
        "ats": "getro",
        "slug": "talent.uvcpartners.com/uvc-partners-2",
    },
    {
        "name": "Valar Ventures",
        "website": "https://valar.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Venionaire Capital",
        "website": "https://www.venionaire.com/careers",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Ventech",
        "website": "https://ventechvc.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Verve Ventures",
        "website": "https://www.verve.vc/join",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Vireo Ventures",
        "website": "https://vireo.vc",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Visionaries Club",
        "website": "https://join.com/companies/visionariesclub",
        "ats": "join",
        "slug": "visionariesclub",
    },
    {
        "name": "Vito One",
        "website": "https://www.viessmann.group:443",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Vorwerk Ventures",
        "website": "https://vorwerkventures.com",
        "ats": "join",
        "slug": "vorwerkventures",
    },
    {
        "name": "Vsquared Ventures",
        "website": "https://vsquared.vc/career",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Vy Capital",
        "website": "https://vycapital.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Wayra",
        "website": "https://wayra.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Wellington Partners",
        "website": "https://wellington-partners.com",
        "ats": "join",
        "slug": "wellington-partners",
    },
    {
        "name": "White Star Capital",
        "website": "https://whitestarcapital.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "World Fund",
        "website": "https://www.worldfund.vc/career",
        "ats": None,
        "slug": None,
    },
    {
        "name": "XAnge",
        "website": "https://www.xange.vc",
        "ats": "join",
        "slug": "xange",
    },
    {
        "name": "Y Combinator",
        "website": "https://ycombinator.com",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Yabeo Capital",
        "website": "https://yabeo.de/jobs",
        "ats": None,
        "slug": None,
    },
    {
        "name": "Ysios Capital",
        "website": "https://ysioscapital.com/join-us",
        "ats": None,
        "slug": None,
    },
]
