"""
VCs OHNE auslesbaren Karrierefeed (Stand 19.09.2026). Der Scanner ignoriert diese Datei.
Gruende: keine oeffentliche Karriereseite, nur Portfolio-Jobboard, JavaScript-only oder Bot-Schutz.
Wenn fuer einen VC ein Feed gefunden wird: Eintrag nach vcs.py verschieben und ats/slug setzen.
"""

NOT_SCANNABLE: list[dict] = [
    {"name": "1750 Ventures VGH Versicherungen", "website": "https://www.1750.ventures/"},
    {"name": "42CAP", "website": "https://www.42cap.com/"},
    {"name": "468 Capital", "website": "https://468cap.com/careers"},
    {"name": "Accel", "website": "https://jobs.accel.com/jobs"},
    {"name": "Acton Capital", "website": "https://www.actoncapital.com"},
    {"name": "Addition", "website": "https://addition.com"},
    {"name": "Albion", "website": "https://albion.vc/"},
    {"name": "allygatr", "website": "https://allygatr.com/careers"},
    {"name": "Alpha Future Funds", "website": "https://alphafuturefunds.com/"},
    {"name": "AM Ventures", "website": "https://www.amventures.com"},
    {"name": "Andreessen Horowitz", "website": "https://jobs.a16z.com/jobs"},
    {"name": "Angel Invest", "website": "https://angelinvest.ventures/"},
    {"name": "another.vc", "website": "https://www.another.vc/"},
    {"name": "Anthemis Group", "website": "https://www.anthemis.com/careers"},
    {"name": "Apeiron Investment Group", "website": "https://apeiron-investments.com/"},
    {"name": "Apollo Health Ventures", "website": "https://www.apollo.vc/"},
    {"name": "APX", "website": "https://apx.vc"},
    {"name": "ARMILAR Venture Partners", "website": "https://www.armilar.com/jobs"},
    {"name": "Atlantic Food Labs", "website": "https://jobsatlanticvc.recruitee.com/"},
    {"name": "Atomico", "website": "https://careers.atomico.com/jobs"},
    {"name": "Auxxo", "website": "https://auxxofemalecatalystfund.notion.site/Join-the-Auxxo-Female-Catalyst-Fund-f7a1f7b8f5f24ab1bba68dd4d0afedc4"},
    {"name": "aws Gründerfonds", "website": "https://www.gruendungsfonds.at/karriere"},
    {"name": "Ballpark Ventures", "website": "https://www.ballparkventures.com/"},
    {"name": "BambooVentures", "website": "https://www.bambooventures.net/careers?tr_uuid=20260919-0833-109a-975f-22fdfdbbf787&fp=-3"},
    {"name": "BayBG", "website": "https://baybg.com"},
    {"name": "be-exponential", "website": "https://www.be-exponential.com/"},
    {"name": "Benchmark", "website": "https://benchmark.com"},
    {"name": "Bessemer Venture Partners", "website": "https://jobs.bvp.com/jobs"},
    {"name": "Blockwall", "website": "https://www.blockwall.vc/"},
    {"name": "BLS Venture Capital", "website": "https://www.bls-venture.de/"},
    {"name": "BMW i Ventures", "website": "https://www.bmwiventures.com"},
    {"name": "Boehringer Ingelheim Venture Fund", "website": "https://www.boehringer-ingelheim-venture.com/careers"},
    {"name": "Bond", "website": "https://www.bondcap.com"},
    {"name": "Boost VC", "website": "https://www.boost.vc/jobs"},
    {"name": "Bpifrance", "website": "https://www.bpifrance.com"},
    {"name": "Breega", "website": "https://jobs.breega.com/"},
    {"name": "Brighteye Ventures", "website": "https://www.brighteyevc.com"},
    {"name": "building10", "website": "https://b10.vc/careers"},
    {"name": "byFounders", "website": "https://byfounders.vc"},
    {"name": "Cadence Growth Capital", "website": "https://www.cadencegrowthcapital.com/"},
    {"name": "Calm/Storm Ventures", "website": "https://www.calmstorm.vc/jobs"},
    {"name": "Capital300", "website": "https://capital300.com"},
    {"name": "Cavalry Ventures", "website": "https://cavalry.vc"},
    {"name": "Cisco Investments", "website": "https://www.ciscoinvestments.com"},
    {"name": "Climentum Capital", "website": "https://climentum.com/"},
    {"name": "Coatue", "website": "https://www.coatue.com"},
    {"name": "CologneInvest", "website": "https://cologne-invest.com"},
    {"name": "CommerzVentures", "website": "https://commerzventures.com"},
    {"name": "Committed Capital", "website": "https://committedcapital.nl/en/"},
    {"name": "Connect Ventures", "website": "https://www.connectventures.co/"},
    {"name": "Crossventures", "website": "https://www.crossventures.de/xkarriere/"},
    {"name": "Daphni", "website": "https://talent.daphni.com/jobs"},
    {"name": "Dawn Capital", "website": "https://jobs.dawncapital.com/jobs"},
    {"name": "DiamondStream Partners", "website": "https://diamondstream.com"},
    {"name": "Digital Health Ventures", "website": "https://dhventures.de/"},
    {"name": "Dragoneer", "website": "https://www.dragoneer.com"},
    {"name": "eCAPITAL", "website": "https://ecapital.vc/jobs/"},
    {"name": "Eight Roads", "website": "https://eightroads.com"},
    {"name": "EKK & Co", "website": "https://www.ekkco.de/"},
    {"name": "Elevat3 Capital", "website": "https://www.elevat3.vc/"},
    {"name": "Encomenda Smart Capital", "website": "https://encomenda.com/"},
    {"name": "endeit", "website": "https://careers.endeit.com/companies"},
    {"name": "Entrepreneur First", "website": "https://www.joinef.com/about/careers/"},
    {"name": "ETF Partners", "website": "https://etfpartners.com"},
    {"name": "Extorel", "website": "https://www.extorel.de"},
    {"name": "Firestartr", "website": "https://www.firestartr.co/careers"},
    {"name": "FirstMark", "website": "https://jobs.firstmark.com/jobs"},
    {"name": "firstminute capital", "website": "https://www.firstminute.capital/about/talent"},
    {"name": "Floor13", "website": "https://www.floor13.de/"},
    {"name": "Fly Ventures", "website": "https://fly.vc"},
    {"name": "Founders Fund", "website": "https://foundersfund.com"},
    {"name": "Fund F", "website": "https://www.fund-f.com"},
    {"name": "G Squared", "website": "https://gsquared.com/"},
    {"name": "Gamma Capital Partners", "website": "https://www.gamma-capital.com"},
    {"name": "GGF", "website": "https://www.ggf.vc/"},
    {"name": "Greylock", "website": "https://greylock.com/jobs/"},
    {"name": "Hannover Digital Investments", "website": "https://www.hannover-digital-invest.com/careers"},
    {"name": "Heartcore Capital", "website": "https://www.heartcore.com"},
    {"name": "Hedosophia", "website": "https://hedosophia.com"},
    {"name": "Henkel Ventures", "website": "https://www.henkel-ventures.com/"},
    {"name": "Hevella Beteiligungen", "website": "https://www.hevella-capital.com"},
    {"name": "Hinge Capital", "website": "https://hingecapital.com/"},
    {"name": "HOWZAT Partners", "website": "https://www.howzatpartners.com/"},
    {"name": "Hummingbird Ventures", "website": "https://www.hummingbird.vc"},
    {"name": "Initial Capital", "website": "https://www.initialcapital.com/"},
    {"name": "Intel Capital", "website": "https://www.intelcapital.com"},
    {"name": "Iris Capital", "website": "https://iriscapital.notion.site/IRIS-Job-board-d23e8c13da7d4623a1d5bfabe794d73a"},
    {"name": "ISAI", "website": "https://isai.welcomekit.co/"},
    {"name": "Isartal Ventures", "website": "https://www.isartal-ventures.de/"},
    {"name": "iVentureCapital", "website": "https://www.iventuregroup.com/de/"},
    {"name": "IVP", "website": "https://www.ivp.com/careers/"},
    {"name": "J.C.M.B. Beteiligungs", "website": "https://www.jcmb.de/"},
    {"name": "JamJar Investments", "website": "https://jobs.jamjarinvestments.com/companies"},
    {"name": "Kerala Ventures", "website": "https://www.kerala.vc/"},
    {"name": "Kernel Capital", "website": "https://www.kernel-capital.com/"},
    {"name": "Kibo Ventures", "website": "https://www.kiboventures.com"},
    {"name": "Kima Ventures", "website": "https://www.kimaventures.com"},
    {"name": "Kindred Capital", "website": "https://kindredcapital.vc"},
    {"name": "Kinnevik", "website": "https://www.kinnevik.com/working-at-kinnevik/career/"},
    {"name": "Kizoo Technology Capital", "website": "https://kizoo.com"},
    {"name": "Kleiner Perkins", "website": "https://www.kleinerperkins.com"},
    {"name": "Kurma Partners", "website": "https://www.kurmapartners.com"},
    {"name": "La Famiglia", "website": "https://www.lafamiglia.vc"},
    {"name": "LSP", "website": "https://eqtgroup.com/about/careers"},
    {"name": "M12", "website": "https://m12.vc"},
    {"name": "Maki.vc", "website": "https://maki.vc"},
    {"name": "Medicxi", "website": "https://www.medicxi.com"},
    {"name": "MMC Ventures", "website": "https://jobs.mmc.vc/jobs"},
    {"name": "Molten Ventures", "website": "https://www.moltenventures.com"},
    {"name": "Monkfish Equity", "website": "https://www.monkfish-equity.com/"},
    {"name": "Motive Partners", "website": "https://motivepartners.com"},
    {"name": "Munich Venture Partners", "website": "https://munichvp.com"},
    {"name": "Mutschler Ventures", "website": "https://www.mutschler-ventures.com/"},
    {"name": "Muzungu Capital", "website": "https://muzungu-capital.com/"},
    {"name": "NAP", "website": "https://nap.vc"},
    {"name": "NEA", "website": "https://nea.com"},
    {"name": "neosfer", "website": "https://neosfer.de/"},
    {"name": "Novartis Venture Fund", "website": "https://www.nvfund.com"},
    {"name": "Pale Blue Dot", "website": "https://paleblue.vc/jobs"},
    {"name": "Passion Capital", "website": "https://passioncapital.com"},
    {"name": "PD Ventures", "website": "https://www.pddigital.de/karriere/"},
    {"name": "Phoenix Contact Innovation Ventures", "website": "https://www.phoenixcontact-innovationventures.com/"},
    {"name": "Pioneer Fund", "website": "https://www.pioneerfund.vc/careers"},
    {"name": "PluMedia", "website": "https://www.plumedia.de/"},
    {"name": "Plural VC", "website": "https://www.plural.vc"},
    {"name": "PMV Venture Capital", "website": "https://www.pmv.eu/en/"},
    {"name": "Porsche Ventures", "website": "https://porsche.ventures"},
    {"name": "Prime Technology Ventures", "website": "https://www.primeventures.com/"},
    {"name": "Prosus Ventures", "website": "https://prosus.com"},
    {"name": "PT1 Ventures", "website": "https://pt1.vc"},
    {"name": "Quadrille Capital", "website": "https://www.quadrillecapital.com/"},
    {"name": "Qualcomm Ventures", "website": "https://www.qualcommventures.com"},
    {"name": "Rebel Fund", "website": "https://www.rebelfund.vc"},
    {"name": "Red River West", "website": "https://www.redriverwest.com"},
    {"name": "Redpoint eventures", "website": "https://careers.redpoint.com/jobs"},
    {"name": "rethink ventures", "website": "https://rethinkventures.com/"},
    {"name": "Ribbit Capital", "website": "https://www.ribbitcap.com"},
    {"name": "RIVUS Capital", "website": "https://www.rivuscapital.com/"},
    {"name": "Robert Bosch Venture Capital", "website": "https://bosch.ventures"},
    {"name": "RockawayX", "website": "https://www.rockawayx.com/careers/venture-analyst"},
    {"name": "Round 2 Capital Partners", "website": "https://round2cap.com/"},
    {"name": "Saarländische Wagnisfinanzierungsgesellschaft (SWG)", "website": "https://swgmbh.de/"},
    {"name": "Salvia", "website": "https://salvia.de/"},
    {"name": "Samos Venture Capital", "website": "https://samos.vc/"},
    {"name": "Seaya", "website": "https://seaya.com"},
    {"name": "SevenVentures", "website": "https://www.commerceandventures.com"},
    {"name": "SGH Capital", "website": "https://www.sghcapital.com/"},
    {"name": "Simon Capital", "website": "https://www.simoncapital.com/"},
    {"name": "Singular", "website": "https://www.singular.vc"},
    {"name": "Sofinnova Partners", "website": "https://sofinnovapartners.com"},
    {"name": "Sound Ventures", "website": "https://www.soundventures.com/"},
    {"name": "Spotlight Ventures", "website": "https://www.spotlightventures.de/"},
    {"name": "SquareOne", "website": "https://www.squareone.vc"},
    {"name": "STARTHUB Ventures", "website": "https://www.starthub-ventures.com/careers"},
    {"name": "Statkraft Ventures", "website": "https://www.statkraftventures.com"},
    {"name": "Stride.VC", "website": "https://stride.vc"},
    {"name": "Structure Capital", "website": "https://structure.vc/"},
    {"name": "Summit Partners", "website": "https://www.summitpartners.com/summit-careers"},
    {"name": "Talis Capital", "website": "https://www.taliscapital.com/"},
    {"name": "Target Global", "website": "https://targetglobal.vc"},
    {"name": "TCV", "website": "https://www.tcv.com"},
    {"name": "Team Global", "website": "https://teamglobal.net/"},
    {"name": "Technologiegründerfonds Sachsen", "website": "https://www.cfh.de"},
    {"name": "TECHVISIONS FONDS", "website": "https://tvf.vc"},
    {"name": "Tengelmann Ventures", "website": "https://tengelmann-ventures.com/portfolio/careerfoundry/"},
    {"name": "Tiger Global", "website": "https://www.tigerglobal.com"},
    {"name": "TMT Investments", "website": "https://tmtinvestments.com/careers"},
    {"name": "tokentus investment", "website": "https://tokentus.com/"},
    {"name": "Trade Ventures", "website": "https://www.tradeventures.com"},
    {"name": "Trind Ventures", "website": "https://trind.vc"},
    {"name": "TRUMPF Venture", "website": "https://www.trumpf.com/de_DE/unternehmen/weitere-taetigkeitsfelder/trumpf-venture/"},
    {"name": "TVM Capital Life Science", "website": "https://tvm-capital.com"},
    {"name": "TX Ventures", "website": "https://www.tx.ventures/"},
    {"name": "Union Square Ventures", "website": "https://jobs.usv.com/jobs"},
    {"name": "VAERING", "website": "https://www.vaering.de/"},
    {"name": "Valar Ventures", "website": "https://valar.com"},
    {"name": "Vality Ventures", "website": "https://vality-ventures.de"},
    {"name": "Velvet Ventures", "website": "https://velvetventures.de/"},
    {"name": "Ventech", "website": "https://ventechvc.com"},
    {"name": "Vireo Ventures", "website": "https://vireo.vc"},
    {"name": "Vito One", "website": "https://www.viessmann.group:443/how/careers"},
    {"name": "Vorsprung Partners", "website": "https://www.vorsprungpartners.com/"},
    {"name": "Vsquared Ventures", "website": "https://vsquared.vc/career/"},
    {"name": "Vy Capital", "website": "https://vycapital.com"},
    {"name": "Wayra", "website": "https://wayra.com"},
    {"name": "White Star Capital", "website": "https://whitestarcapital.com"},
    {"name": "Yabeo Capital", "website": "https://ceracare.co.uk/"},
    {"name": "Revent", "website": "https://careers.revent.vc/jobs"},  # Jobboard laedt per JavaScript
    {"name": "10x Founders", "website": "https://10xfounders.jobs.personio.com/"},  # Personio-XML-Feed deaktiviert
]
